---
# tasks file for roles/nginx 
#- name: Update apt cache
 # apt:
  # update_cache: yes
  #cache_valid_time: 3600

  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Deploy index page
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
    notify: restart nginx

  - name: Ensure nginx is started and enabled
    service:
       name: nginx
       state: started
       enabled: yes
