---
- name: Install and start Nginx
  hosts: web
  become: yes


  tasks:

   - name: Update apt cache
     apt:
      update_cache: yes
      cache_valid_time: 3600

   - name: Install nginx
     apt:
      name: nginx
      state: present

   - name: Deploy custom index page
     copy:
       src: files/index.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: '0644'

   - name: Ensure nginx is started and enabled
     service:
      name: nginx
      state: started
      enabled: yes
