 name: Ansible Deploy


 on:
  push:
   branches:
      - main

 jobs:
  deploy:
    runs-on: ubuntu-latest

 defaults: 
   run:
    working-directory: ansible

  steps:
   - name: Checkout repository
     uses: actions/checkout@v4


   - name: Install Ansible
     run: |
       sudo apt update
       sudo apt install -y ansible


   - name: Setup SSH key
     run: |
       mkdir -p ~/.ssh
       echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
       chmod 600 ~/.ssh/id_ed25519

   - name: Add server to known_hosts
     run: |
       ssh-keyscan -H ${{ secrets.ANSIBLE_HOST }} .. ~/.ssh/known_hosts


   - name: Setup vault password
     run: |
      echo "${{ secrets.VAULT_PASS }}" > .vault_pass

  - name: Run Ansible Playbook
    run: |
     ansible-playbook install_site.yml -i inventories/prod/hosts.yml
